### ISSUE TITLE
helm install fails with "k8s-monitoring/templates/tests/test.yaml" at <index .Subcharts "grafana-agent">

### ISSUE THREAD

**Issue by LingamEswar** [grafana/k8s-monitoring-helm#493] opened 2024-04-26 16:21 UTC
HI team,
We are trying to install k8s-monitoring chart of v0.12.0 and while installing we are facing an issue 

Error: template: k8s-monitoring/templates/tests/test.yaml:106:54: executing "k8s-monitoring/templates/tests/test.yaml" at <index .Subcharts "grafana-agent">: error calling index: index of untyped nil

I have check in the repo list and i am able to see the grafana-agent chart as well. But not sure why the issue is.

Can you please help here as soon as possible.

Tried with 0.9.3 and latest version as well. But resulted in same issue.

**Comment by petewall** [comment] 2024-04-26 17:19
Closing as a duplicate of #494

**Closed by petewall** 2024-04-26 17:19 UTC
